<h1>静的絵文字</h1>
{emoji SUN}:SUN<br />
{emoji CLOUD}:CLOUD<br />
{emoji RAIN}:RAIN<br />
{emoji SNOW}:SNOW<br />
{emoji THUNDER}:THUNDER<br />
{emoji TYPHOON}:TYPHOON<br />
{emoji FOG}:FOG<br />
{emoji DRIZZLE}:DRIZZLE<br />
{emoji ARIES}:ARIES<br />
{emoji TAURUS}:TAURUS<br />
{emoji GEMINI}:GEMINI<br />
{emoji CANCER}:CANCER<br />
{emoji LEO}:LEO<br />
{emoji VIRGO}:VIRGO<br />
{emoji LIBRA}:LIBRA<br />
{emoji SCORPIO}:SCORPIO<br />
{emoji SAGITTARIUS}:SAGITTARIUS<br />
{emoji CAPRICORN}:CAPRICORN<br />
{emoji AQUARIUS}:AQUARIUS<br />
{emoji PISCES}:PISCES<br />
{emoji SPORTS1}:SPORTS1<br />
{emoji BASEBALL}:BASEBALL<br />
{emoji GOLF}:GOLF<br />
{emoji TENNIS}:TENNIS<br />
{emoji SOCCER}:SOCCER<br />
{emoji SKIING}:SKIING<br />
{emoji BASKETBALL}:BASKETBALL<br />
{emoji MOTOR_SPORTS}
{emoji POKEBERU}:POKEBERU<br />
{emoji TRAIN}:TRAIN<br />
{emoji SUBWAY}:SUBWAY<br />
{emoji SHINKANSEN}:SHINKANSEN<br />
{emoji CAR1}:CAR1<br />
{emoji CAR2}:CAR2<br />
{emoji BUS}:BUS<br />
{emoji SHIP}:SHIP<br />
{emoji PLAIN}:PLAIN<br />
{emoji HOME}:HOME<br />
{emoji BUILDING}:BUILDING<br />
{emoji POST_OFFICE}
{emoji HOSPITAL}:HOSPITAL<br />
{emoji BANK}:BANK<br />
{emoji ATM}:ATM<br />
{emoji HOTEL}:HOTEL<br />
{emoji CONVENI}:CONVENI<br />
{emoji GAS}:GAS<br />
{emoji PARKING}:PARKING<br />
{emoji SIGN}:SIGN<br />
{emoji TOILE}:TOILE<br />
{emoji RESTRAN}:RESTRAN<br />
{emoji BAR}:BAR<br />
{emoji BEER}:BEER<br />
{emoji FAST_FOOD}
{emoji SHOP}:SHOP<br />
{emoji SALON}:SALON<br />
{emoji KARAOKE}:KARAOKE<br />
{emoji MOVIE}:MOVIE<br />
{emoji YA1}:YA1<br />
{emoji TOYS}:TOYS<br />
{emoji ENTAME}:ENTAME<br />
{emoji ART}:ART<br />
{emoji PLAY}:PLAY<br />
{emoji EVENT}:EVENT<br />
{emoji TICKET}:TICKET<br />
{emoji SMOKING}:SMOKING<br />
{emoji NO_SMOKING}
{emoji CAMERA}:CAMERA<br />
{emoji BAG}:BAG<br />
{emoji BOOK}:BOOK<br />
{emoji RIBBON}:RIBBON<br />
{emoji PRESENT}:PRESENT<br />
{emoji BIRTHDAY}:BIRTHDAY<br />
{emoji PHONE}:PHONE<br />
{emoji MOBILE}:MOBILE<br />
{emoji MEMO}:MEMO<br />
{emoji TV}:TV<br />
{emoji GAME}:GAME<br />
{emoji CD}:CD<br />
{emoji HEART1}:HEART1<br />
{emoji SPADE}:SPADE<br />
{emoji DIAMOND}:DIAMOND<br />
{emoji CLUB}:CLUB<br />
{emoji EYE}:EYE<br />
{emoji EAR}:EAR<br />
{emoji HAND1}:HAND1<br />
{emoji HAND2}:HAND2<br />
{emoji HAND3}:HAND3<br />
{emoji YA2}:YA2<br />
{emoji YA3}:YA3<br />
{emoji FOOT}:FOOT<br />
{emoji SHOES}:SHOES<br />
{emoji GLASSES}:GLASSES<br />
{emoji WHEELCHAIR}:WHEELCHAIR<br />
{emoji MOON1}:MOON1<br />
{emoji MOON2}:MOON2<br />
{emoji MOON3}:MOON3<br />
{emoji MOON4}:MOON4<br />
{emoji MOON5}:MOON5<br />
{emoji DOG}:DOG<br />
{emoji CAT1}:CAT1<br />
{emoji RESORT}:RESORT<br />
{emoji CHRISTMAS}:CHRISTMAS<br />
{emoji YA4}:YA4<br />
{emoji PHONETO}:PHONETO<br />
{emoji MAILTO}:MAILTO<br />
{emoji FAXTO}:FAXTO<br />
{emoji IMODE1}:IMODE1<br />
{emoji IMODE2}:IMODE2<br />
{emoji MAIL}:MAIL<br />
{emoji DOCOMO}:DOCOMO<br />
{emoji DOCOMO_POINT}
{emoji CHARGE}:CHARGE<br />
{emoji FREE}:FREE<br />
{emoji ID}:ID<br />
{emoji PASSWORD}:PASSWORD<br />
{emoji RETURN}:RETURN<br />
{emoji CLEAR}:CLEAR<br />
{emoji SEARCH}:SEARCH<br />
{emoji NEW}:NEW<br />
{emoji GPS}:GPS<br />
{emoji FREEDIAL}:FREEDIAL<br />
{emoji SHARPDIAL}:SHARPDIAL<br />
{emoji Q}:Q<br />
{emoji NUM01}:NUM01<br />
{emoji NUM02}:NUM02<br />
{emoji NUM03}:NUM03<br />
{emoji NUM04}:NUM04<br />
{emoji NUM05}:NUM05<br />
{emoji NUM06}:NUM06<br />
{emoji NUM07}:NUM07<br />
{emoji NUM08}:NUM08<br />
{emoji NUM09}:NUM09<br />
{emoji NUM00}:NUM00<br />
{emoji OK1}:OK1<br />
{emoji HEART2}:HEART2<br />
{emoji HEART3}:HEART3<br />
{emoji HEARTBREAK}:HEARTBREAK<br />
{emoji HEART4}:HEART4<br />
{emoji FACE1}:FACE1<br />
{emoji FACE2}:FACE2<br />
{emoji FACE3}:FACE3<br />
{emoji FACE4}:FACE4<br />
{emoji FACE5}:FACE5<br />
{emoji GOOD}:GOOD<br />
{emoji ONPU}:ONPU<br />
{emoji ONSEN}:ONSEN<br />
{emoji MIDASHI}:MIDASHI<br />
{emoji KISS}:KISS<br />
{emoji KIRAKIRA}:KIRAKIRA<br />
{emoji HINT}:HINT<br />
{emoji ANGER}:ANGER<br />
{emoji PUNCH}:PUNCH<br />
{emoji BOMB}:BOMB<br />
{emoji MOOD}:MOOD<br />
{emoji BAD}:BAD<br />
{emoji SLEEP}:SLEEP<br />
{emoji BIKKURI}:BIKKURI<br />
{emoji QUESTION}:QUESTION<br />
{emoji BIKKURI2}:BIKKURI2<br />
{emoji DON}:DON<br />
{emoji ASE1}:ASE1<br />
{emoji ASE2}:ASE2<br />
{emoji DASH}:DASH<br />
{emoji SIGN1}:SIGN1<br />
{emoji SIGN2}:SIGN2<br />
{emoji CLAPPERBOARD}:CLAPPERBOARD<br />
{emoji FUKURO}:FUKURO<br />
{emoji PEN1}:PEN1<br />
{emoji SHADOW}:SHADOW<br />
{emoji CHAIR}:CHAIR<br />
{emoji NIGHT}:NIGHT<br />
{emoji SOON}:SOON<br />
{emoji ON}:ON<br />
{emoji END}:END<br />
{emoji SCHEDULE}:SCHEDULE<br />
{emoji IAPP1}:IAPP1<br />
{emoji IAPP2}:IAPP2<br />
{emoji TSHIRT}:TSHIRT<br />
{emoji GAMA}:GAMA<br />
{emoji MAKEUP}:MAKEUP<br />
{emoji ZUBON}:ZUBON<br />
{emoji SPORTS2}:SPORTS2<br />
{emoji TIN}:TIN<br />
{emoji DOOR}:DOOR<br />
{emoji MONEY}:MONEY<br />
{emoji PC}:PC<br />
{emoji HEART_MAIL}
{emoji TOOL}:TOOL<br />
{emoji PEN2}:PEN2<br />
{emoji CROWN}:CROWN<br />
{emoji RING}:RING<br />
{emoji WATCH1}:WATCH1<br />
{emoji BICYCLE}:BICYCLE<br />
{emoji CUP}:CUP<br />
{emoji WATCH2}:WATCH2<br />
{emoji FACE6}:FACE6<br />
{emoji FACE7}:FACE7<br />
{emoji FACE8}:FACE8<br />
{emoji FACE9}:FACE9<br />
{emoji FACE10}:FACE10<br />
{emoji FACE11}:FACE11<br />
{emoji FACE12}:FACE12<br />
{emoji OK2}:OK2<br />
{emoji FACE13}:FACE13<br />
{emoji FACE14}:FACE14<br />
{emoji FACE15}:FACE15<br />
{emoji FACE16}:FACE16<br />
{emoji CAT2}:CAT2<br />
{emoji FACE17}:FACE17<br />
{emoji NG}:NG<br />
{emoji CLIP}:CLIP<br />
{emoji COPYRIGHT}:COPYRIGHT<br />
{emoji TM}:TM<br />
{emoji RUN}:RUN<br />
{emoji MARUHI}:MARUHI<br />
{emoji UPDATE}:UPDATE<br />
{emoji R}:R<br />
{emoji ALERT}:ALERT<br />
{emoji KIN}:KIN<br />
{emoji AKI}:AKI<br />
{emoji GOU}:GOU<br />
{emoji MAN}:MAN<br />
{emoji YA5}:YA5<br />
{emoji YA6}:YA6<br />
{emoji SCHOOL}:SCHOOL<br />
{emoji WAVE}:WAVE<br />
{emoji FUJI}:FUJI<br />
{emoji FOURLEAF}:FOURLEAF<br />
{emoji CHERRY}:CHERRY<br />
{emoji TULIP}:TULIP<br />
{emoji BANANA}:BANANA<br />
{emoji APPLE}:APPLE<br />
{emoji BUD}:BUD<br />
{emoji MOMIJI}:MOMIJI<br />
{emoji SAKURA}:SAKURA<br />
{emoji ONIGIRI}:ONIGIRI<br />
{emoji CAKE}:CAKE<br />
{emoji TOKURI}:TOKURI<br />
{emoji DONBURI}:DONBURI<br />
{emoji BREAD}:BREAD<br />
{emoji SNAIL}:SNAIL<br />
{emoji HIYOKO}:HIYOKO<br />
{emoji PENGIN}:PENGIN<br />
{emoji FISH}:FISH<br />
{emoji FACE18}:FACE18<br />
{emoji FACE19}:FACE19<br />
{emoji HORSE}:HORSE<br />
{emoji PIG}:PIG<br />
{emoji WINE}:WINE<br />
{emoji FACE20}:FACE20<br />