<h3>ユーザー</h3>
    <ul>
        <li>{$body.user.name}</li>
        <li>{$body.user.age}</li>
    </ul>
<h3>ブログ</h3>
    <ul>
        <li>{$body.blog.name}</li>
    </ul>
<h3>最新記事</h3>
    <ul>
        <li>{$body.new.title}</li>
    </ul>