<h2>AOPテスト</h2>
<h3>オリジナル</h3>
{$original|@printa}
<h3>Beforeアドバイス</h3>
<p>入力を変更(idを2に）</p>
{$before|@printa}
<h3>Afterアドバイス</h3>
<p>出力を変更(ageを付加）</p>
{$after|@printa}
<h3>Aroundアドバイス</h3>
<p>前処理と後処理を付加(タイマーをスタート、ストップしてsecを付加）</p>
{$around|@printa}
<h3>Retruningアドバイス</h3>
<p>エラーでなければ後処理を付加</p>
{$returning|@printa}
<h3>Throwingアドバイス(1)</h3>
<p>PEARエラーならば後処理を付加</p>
{$throwing|@printa}
<h3>Throwingアドバイス(2)</h3>
<p>例外ならば後処理を付加</p>
{$throwing2|@printa}
<h3>上記全てのアドバイス適用</h3>
{$all|@printa}
<h3>aroundアドバイス再利用(idを3に）</h3>
{$around2|@printa}
